method: onet
data:
  path: data/ShapeNet
  classes: ['03001627']
  img_folder: img_choy2016
  img_size: 224 
  points_subsample: 2048 
  uda_path: data/pix3d_processed
  uda_path_train: data/target_domain/bg # used for training. in the future, make this bigger (eg, 6781 chair models in shapenet)
  uda_classes: ['chair']
  uda_img_folder: img_pix3d # used for testing
  uda_bg_configure: "bg"
  voxels_file: null # check in config.py for onet
model:
  encoder_latent: null # This disables the latent vector z for generation
  z_dim: 0
  decoder: cbatchnorm
  encoder: resnet18
  c_dim: 256 # size of latent code for image
training:
  out_dir:  out/DA_related/onet_chair_DANN_optimized_bg
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 20000
  validate_every: 20000
  backup_every: 10000
  uda_type: dann
  num_epochs: 1000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: model.pt
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32 
  upsampling_steps: 2

